// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: external_provider.proto

package externalproviderpb

import (
	ateapipb "github.com/agent-substrate/substrate/pkg/proto/ateapipb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelKind identifies the in-cluster service surface carried by a channel,
// independently of the local runtime or model product.
type ChannelKind int32

const (
	ChannelKind_CHANNEL_KIND_UNSPECIFIED    ChannelKind = 0
	ChannelKind_CHANNEL_KIND_EXECUTION_GRPC ChannelKind = 1
	ChannelKind_CHANNEL_KIND_ACTOR_INGRESS  ChannelKind = 2
	ChannelKind_CHANNEL_KIND_ACTOR_EGRESS   ChannelKind = 3
)

// Enum value maps for ChannelKind.
var (
	ChannelKind_name = map[int32]string{
		0: "CHANNEL_KIND_UNSPECIFIED",
		1: "CHANNEL_KIND_EXECUTION_GRPC",
		2: "CHANNEL_KIND_ACTOR_INGRESS",
		3: "CHANNEL_KIND_ACTOR_EGRESS",
	}
	ChannelKind_value = map[string]int32{
		"CHANNEL_KIND_UNSPECIFIED":    0,
		"CHANNEL_KIND_EXECUTION_GRPC": 1,
		"CHANNEL_KIND_ACTOR_INGRESS":  2,
		"CHANNEL_KIND_ACTOR_EGRESS":   3,
	}
)

func (x ChannelKind) Enum() *ChannelKind {
	p := new(ChannelKind)
	*p = x
	return p
}

func (x ChannelKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelKind) Descriptor() protoreflect.EnumDescriptor {
	return file_external_provider_proto_enumTypes[0].Descriptor()
}

func (ChannelKind) Type() protoreflect.EnumType {
	return &file_external_provider_proto_enumTypes[0]
}

func (x ChannelKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelKind.Descriptor instead.
func (ChannelKind) EnumDescriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{0}
}

type ExternalProviderEnrollmentScope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAtespace   string                 `protobuf:"bytes,1,opt,name=owner_atespace,json=ownerAtespace,proto3" json:"owner_atespace,omitempty"`
	WorkerNamespace string                 `protobuf:"bytes,2,opt,name=worker_namespace,json=workerNamespace,proto3" json:"worker_namespace,omitempty"`
	WorkerPool      string                 `protobuf:"bytes,3,opt,name=worker_pool,json=workerPool,proto3" json:"worker_pool,omitempty"`
	MaxSlots        uint32                 `protobuf:"varint,4,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	// slot_policy is the exact immutable policy to bind to the enrollment. A
	// request MUST leave digest empty; the server canonicalizes profiles and
	// returns the authoritative digest in the response.
	SlotPolicy    *SlotCapabilityPolicy `protobuf:"bytes,5,opt,name=slot_policy,json=slotPolicy,proto3" json:"slot_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalProviderEnrollmentScope) Reset() {
	*x = ExternalProviderEnrollmentScope{}
	mi := &file_external_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalProviderEnrollmentScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalProviderEnrollmentScope) ProtoMessage() {}

func (x *ExternalProviderEnrollmentScope) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalProviderEnrollmentScope.ProtoReflect.Descriptor instead.
func (*ExternalProviderEnrollmentScope) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalProviderEnrollmentScope) GetOwnerAtespace() string {
	if x != nil {
		return x.OwnerAtespace
	}
	return ""
}

func (x *ExternalProviderEnrollmentScope) GetWorkerNamespace() string {
	if x != nil {
		return x.WorkerNamespace
	}
	return ""
}

func (x *ExternalProviderEnrollmentScope) GetWorkerPool() string {
	if x != nil {
		return x.WorkerPool
	}
	return ""
}

func (x *ExternalProviderEnrollmentScope) GetMaxSlots() uint32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *ExternalProviderEnrollmentScope) GetSlotPolicy() *SlotCapabilityPolicy {
	if x != nil {
		return x.SlotPolicy
	}
	return nil
}

type CreateExternalProviderEnrollmentRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Scope         *ExternalProviderEnrollmentScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Ttl           *durationpb.Duration             `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalProviderEnrollmentRequest) Reset() {
	*x = CreateExternalProviderEnrollmentRequest{}
	mi := &file_external_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalProviderEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalProviderEnrollmentRequest) ProtoMessage() {}

func (x *CreateExternalProviderEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalProviderEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*CreateExternalProviderEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExternalProviderEnrollmentRequest) GetScope() *ExternalProviderEnrollmentScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CreateExternalProviderEnrollmentRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type CreateExternalProviderEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentUid string                 `protobuf:"bytes,1,opt,name=enrollment_uid,json=enrollmentUid,proto3" json:"enrollment_uid,omitempty"`
	// enrollment_credential is an opaque, single-use bearer credential. The
	// server persists only its digest and never returns these bytes again.
	EnrollmentCredential []byte                           `protobuf:"bytes,2,opt,name=enrollment_credential,json=enrollmentCredential,proto3" json:"enrollment_credential,omitempty"`
	ExpiresAt            *timestamppb.Timestamp           `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope                *ExternalProviderEnrollmentScope `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateExternalProviderEnrollmentResponse) Reset() {
	*x = CreateExternalProviderEnrollmentResponse{}
	mi := &file_external_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalProviderEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalProviderEnrollmentResponse) ProtoMessage() {}

func (x *CreateExternalProviderEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalProviderEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*CreateExternalProviderEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExternalProviderEnrollmentResponse) GetEnrollmentUid() string {
	if x != nil {
		return x.EnrollmentUid
	}
	return ""
}

func (x *CreateExternalProviderEnrollmentResponse) GetEnrollmentCredential() []byte {
	if x != nil {
		return x.EnrollmentCredential
	}
	return nil
}

func (x *CreateExternalProviderEnrollmentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateExternalProviderEnrollmentResponse) GetScope() *ExternalProviderEnrollmentScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type RevokeExternalProviderRegistrationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistrationUid string                 `protobuf:"bytes,1,opt,name=registration_uid,json=registrationUid,proto3" json:"registration_uid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeExternalProviderRegistrationRequest) Reset() {
	*x = RevokeExternalProviderRegistrationRequest{}
	mi := &file_external_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeExternalProviderRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeExternalProviderRegistrationRequest) ProtoMessage() {}

func (x *RevokeExternalProviderRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeExternalProviderRegistrationRequest.ProtoReflect.Descriptor instead.
func (*RevokeExternalProviderRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeExternalProviderRegistrationRequest) GetRegistrationUid() string {
	if x != nil {
		return x.RegistrationUid
	}
	return ""
}

type RevokeExternalProviderRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeExternalProviderRegistrationResponse) Reset() {
	*x = RevokeExternalProviderRegistrationResponse{}
	mi := &file_external_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeExternalProviderRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeExternalProviderRegistrationResponse) ProtoMessage() {}

func (x *RevokeExternalProviderRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeExternalProviderRegistrationResponse.ProtoReflect.Descriptor instead.
func (*RevokeExternalProviderRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{4}
}

// EnrollRequest is intentionally empty. The enrollment credential is carried
// only in gRPC authorization metadata.
type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_external_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{5}
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registration_uid is a stable, opaque, non-secret server-assigned identity
	// with the same character and 253-byte bounds required by ConnectHello.
	RegistrationUid string `protobuf:"bytes,1,opt,name=registration_uid,json=registrationUid,proto3" json:"registration_uid,omitempty"`
	// refresh_credential is scoped to MintSessionToken. The client stores these
	// 1..4096 unpadded base64url bytes as a secret and sends them as the Bearer
	// token.
	RefreshCredential []byte `protobuf:"bytes,2,opt,name=refresh_credential,json=refreshCredential,proto3" json:"refresh_credential,omitempty"`
	// slot_policy is the immutable, server-owned capability policy bound to the
	// new registration. Clients may reference its profile IDs but cannot extend
	// the sandbox classes, scheduling labels, slot counts, or exact capacities
	// granted by it.
	SlotPolicy    *SlotCapabilityPolicy `protobuf:"bytes,3,opt,name=slot_policy,json=slotPolicy,proto3" json:"slot_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_external_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollResponse) GetRegistrationUid() string {
	if x != nil {
		return x.RegistrationUid
	}
	return ""
}

func (x *EnrollResponse) GetRefreshCredential() []byte {
	if x != nil {
		return x.RefreshCredential
	}
	return nil
}

func (x *EnrollResponse) GetSlotPolicy() *SlotCapabilityPolicy {
	if x != nil {
		return x.SlotPolicy
	}
	return nil
}

type MintSessionTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registration_uid must match the registration bound to the refresh
	// credential in authorization metadata.
	RegistrationUid string `protobuf:"bytes,1,opt,name=registration_uid,json=registrationUid,proto3" json:"registration_uid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintSessionTokenRequest) Reset() {
	*x = MintSessionTokenRequest{}
	mi := &file_external_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSessionTokenRequest) ProtoMessage() {}

func (x *MintSessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSessionTokenRequest.ProtoReflect.Descriptor instead.
func (*MintSessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{7}
}

func (x *MintSessionTokenRequest) GetRegistrationUid() string {
	if x != nil {
		return x.RegistrationUid
	}
	return ""
}

type MintSessionTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_token is scoped to Connect. The client sends these 1..4096
	// unpadded base64url bytes as the Bearer token and never copies them into
	// ClientFrame.
	SessionToken []byte `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// expires_at MUST be present, valid, and later than the server's issuance
	// time. A new Connect rejects session_token at or after this time. Expiry is
	// checked only during the Connect handshake and does not terminate an
	// already accepted stream.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// slot_policy repeats the immutable registration policy so a client can
	// recover its non-secret profile configuration without re-enrollment.
	SlotPolicy    *SlotCapabilityPolicy `protobuf:"bytes,3,opt,name=slot_policy,json=slotPolicy,proto3" json:"slot_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintSessionTokenResponse) Reset() {
	*x = MintSessionTokenResponse{}
	mi := &file_external_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSessionTokenResponse) ProtoMessage() {}

func (x *MintSessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSessionTokenResponse.ProtoReflect.Descriptor instead.
func (*MintSessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{8}
}

func (x *MintSessionTokenResponse) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *MintSessionTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *MintSessionTokenResponse) GetSlotPolicy() *SlotCapabilityPolicy {
	if x != nil {
		return x.SlotPolicy
	}
	return nil
}

// ClientFrame is one frame sent by the external provider.
//
// The first frame MUST contain hello, MUST set session_generation to zero, and
// MUST be no larger than 1 MiB serialized. hello is forbidden after the first
// frame. No other client frame may be sent until the server replies with a
// ready frame. Every subsequent client frame MUST echo the nonzero generation
// from that ready frame; a missing or stale generation is a protocol error. The
// broker validates the generation against the registration and generation
// bound to this gRPC stream; it never trusts the client-echoed integer as
// authority. Exactly one frame member MUST be set. Every client frame MUST be
// no larger than 1 MiB serialized.
type ClientFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionGeneration uint64                 `protobuf:"varint,1,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Open
	//	*ClientFrame_OpenAck
	//	*ClientFrame_Data
	//	*ClientFrame_HalfClose
	//	*ClientFrame_Reset_
	//	*ClientFrame_Heartbeat
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_external_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ClientFrame) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetHello() *ConnectHello {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetOpen() *OpenChannel {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ClientFrame) GetOpenAck() *OpenChannelAck {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_OpenAck); ok {
			return x.OpenAck
		}
	}
	return nil
}

func (x *ClientFrame) GetData() *ChannelData {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ClientFrame) GetHalfClose() *HalfCloseChannel {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return nil
}

func (x *ClientFrame) GetReset_() *ResetChannel {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ClientFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Hello struct {
	Hello *ConnectHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Open struct {
	Open *OpenChannel `protobuf:"bytes,3,opt,name=open,proto3,oneof"`
}

type ClientFrame_OpenAck struct {
	OpenAck *OpenChannelAck `protobuf:"bytes,4,opt,name=open_ack,json=openAck,proto3,oneof"`
}

type ClientFrame_Data struct {
	Data *ChannelData `protobuf:"bytes,5,opt,name=data,proto3,oneof"`
}

type ClientFrame_HalfClose struct {
	HalfClose *HalfCloseChannel `protobuf:"bytes,6,opt,name=half_close,json=halfClose,proto3,oneof"`
}

type ClientFrame_Reset_ struct {
	Reset_ *ResetChannel `protobuf:"bytes,7,opt,name=reset,proto3,oneof"`
}

type ClientFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,8,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Frame() {}

func (*ClientFrame_Open) isClientFrame_Frame() {}

func (*ClientFrame_OpenAck) isClientFrame_Frame() {}

func (*ClientFrame_Data) isClientFrame_Frame() {}

func (*ClientFrame_HalfClose) isClientFrame_Frame() {}

func (*ClientFrame_Reset_) isClientFrame_Frame() {}

func (*ClientFrame_Heartbeat) isClientFrame_Frame() {}

// ServerFrame is one frame sent by the broker.
//
// The first frame MUST contain ready and a nonzero session_generation. The
// broker allocates generations monotonically per registration. Establishing a
// newer generation atomically stops routing to lower generations and closes
// their Connect RPCs with ABORTED. Every later server frame on the stream MUST
// carry the same generation, and the client MUST reject a missing or mismatched
// generation. Exactly one frame member MUST be set. Every server frame MUST be
// no larger than 1 MiB serialized.
type ServerFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionGeneration uint64                 `protobuf:"varint,1,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Ready
	//	*ServerFrame_Open
	//	*ServerFrame_OpenAck
	//	*ServerFrame_Data
	//	*ServerFrame_HalfClose
	//	*ServerFrame_Reset_
	//	*ServerFrame_Heartbeat
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_external_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ServerFrame) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetReady() *ConnectReady {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ServerFrame) GetOpen() *OpenChannel {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ServerFrame) GetOpenAck() *OpenChannelAck {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_OpenAck); ok {
			return x.OpenAck
		}
	}
	return nil
}

func (x *ServerFrame) GetData() *ChannelData {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ServerFrame) GetHalfClose() *HalfCloseChannel {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return nil
}

func (x *ServerFrame) GetReset_() *ResetChannel {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ServerFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Ready struct {
	Ready *ConnectReady `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type ServerFrame_Open struct {
	Open *OpenChannel `protobuf:"bytes,3,opt,name=open,proto3,oneof"`
}

type ServerFrame_OpenAck struct {
	OpenAck *OpenChannelAck `protobuf:"bytes,4,opt,name=open_ack,json=openAck,proto3,oneof"`
}

type ServerFrame_Data struct {
	Data *ChannelData `protobuf:"bytes,5,opt,name=data,proto3,oneof"`
}

type ServerFrame_HalfClose struct {
	HalfClose *HalfCloseChannel `protobuf:"bytes,6,opt,name=half_close,json=halfClose,proto3,oneof"`
}

type ServerFrame_Reset_ struct {
	Reset_ *ResetChannel `protobuf:"bytes,7,opt,name=reset,proto3,oneof"`
}

type ServerFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,8,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerFrame_Ready) isServerFrame_Frame() {}

func (*ServerFrame_Open) isServerFrame_Frame() {}

func (*ServerFrame_OpenAck) isServerFrame_Frame() {}

func (*ServerFrame_Data) isServerFrame_Frame() {}

func (*ServerFrame_HalfClose) isServerFrame_Frame() {}

func (*ServerFrame_Reset_) isServerFrame_Frame() {}

func (*ServerFrame_Heartbeat) isServerFrame_Frame() {}

// ConnectHello declares the complete set of execution slots available through
// this live session. It contains no credential, token, endpoint, route, or
// provider-generated execution/locality identity.
//
// registration_uid must match the session credential. slots MUST contain
// between 1 and 256 entries, sorted lexicographically by slot_id with no
// duplicates. The broker rejects the whole hello on any invalid slot; it does
// not partially accept a declaration. Omitting a previously declared slot
// makes it unavailable for this session but does not request deletion of its
// durable identity. Exactly one declared slot maps to exactly one Worker.
type ConnectHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registration_uid is nonempty, at most 253 ASCII characters, and contains
	// only letters, digits, '.', '_', '~', or '-' with an alphanumeric first and
	// last character.
	RegistrationUid string          `protobuf:"bytes,1,opt,name=registration_uid,json=registrationUid,proto3" json:"registration_uid,omitempty"`
	Slots           []*ExternalSlot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	// protocol_version MUST equal 2 or 3. Version 3 adds the actor-egress
	// credential bootstrap. Version 2 remains accepted for execution and
	// ingress compatibility, but every client-opened ACTOR_EGRESS channel is
	// rejected because it cannot carry generation-bound actor credentials.
	ProtocolVersion uint32 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// slot_policy_digest MUST equal the lowercase SHA-256 digest issued for the
	// authenticated registration. It prevents a client from silently using a
	// stale profile interpretation.
	SlotPolicyDigest string `protobuf:"bytes,4,opt,name=slot_policy_digest,json=slotPolicyDigest,proto3" json:"slot_policy_digest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectHello) Reset() {
	*x = ConnectHello{}
	mi := &file_external_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectHello) ProtoMessage() {}

func (x *ConnectHello) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectHello.ProtoReflect.Descriptor instead.
func (*ConnectHello) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectHello) GetRegistrationUid() string {
	if x != nil {
		return x.RegistrationUid
	}
	return ""
}

func (x *ConnectHello) GetSlots() []*ExternalSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ConnectHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ConnectHello) GetSlotPolicyDigest() string {
	if x != nil {
		return x.SlotPolicyDigest
	}
	return ""
}

// ExternalSlot is provider-neutral scheduling information for one stable slot.
// The broker derives Worker execution_identity and locality_identity from the
// authenticated registration and slot_id; clients never send those identities.
type ExternalSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slot_id is stable within registration_uid. It is 1..253 ASCII characters,
	// starts and ends with an ASCII letter or digit, and otherwise contains only
	// letters, digits, '.', '_', '~', or '-'.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// sandbox_class is reserved for the pre-policy wire shape and MUST be empty.
	// The broker derives the trusted sandbox class from profile_id.
	SandboxClass string `protobuf:"bytes,2,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	// labels is reserved for the pre-policy wire shape and MUST be empty. The
	// broker derives trusted scheduling labels from profile_id and the pinned
	// WorkerPool.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// capacity is reserved for the pre-policy wire shape and MUST be absent. The
	// broker derives exact trusted capacity from profile_id.
	Capacity *ateapipb.WorkerCapacity `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// profile_id selects one profile from the registration's immutable
	// server-owned slot policy.
	ProfileId     string `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalSlot) Reset() {
	*x = ExternalSlot{}
	mi := &file_external_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalSlot) ProtoMessage() {}

func (x *ExternalSlot) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalSlot.ProtoReflect.Descriptor instead.
func (*ExternalSlot) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{12}
}

func (x *ExternalSlot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ExternalSlot) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *ExternalSlot) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ExternalSlot) GetCapacity() *ateapipb.WorkerCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *ExternalSlot) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

// SlotCapabilityPolicy is immutable authority issued by the server at
// enrollment. Profiles are sorted by profile_id and digest is the lowercase
// SHA-256 of the server's versioned canonical encoding.
type SlotCapabilityPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Profiles      []*SlotProfile         `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotCapabilityPolicy) Reset() {
	*x = SlotCapabilityPolicy{}
	mi := &file_external_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotCapabilityPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCapabilityPolicy) ProtoMessage() {}

func (x *SlotCapabilityPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCapabilityPolicy.ProtoReflect.Descriptor instead.
func (*SlotCapabilityPolicy) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{13}
}

func (x *SlotCapabilityPolicy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SlotCapabilityPolicy) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *SlotCapabilityPolicy) GetProfiles() []*SlotProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// SlotProfile grants a bounded, provider-neutral scheduling capability. A
// launcher or product name is not a sandbox class.
type SlotProfile struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ProfileId     string                   `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	SandboxClass  string                   `protobuf:"bytes,2,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	Labels        map[string]string        `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxSlots      uint32                   `protobuf:"varint,4,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	Capacity      *ateapipb.WorkerCapacity `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotProfile) Reset() {
	*x = SlotProfile{}
	mi := &file_external_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotProfile) ProtoMessage() {}

func (x *SlotProfile) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotProfile.ProtoReflect.Descriptor instead.
func (*SlotProfile) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{14}
}

func (x *SlotProfile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SlotProfile) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *SlotProfile) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SlotProfile) GetMaxSlots() uint32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *SlotProfile) GetCapacity() *ateapipb.WorkerCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

// ConnectReady accepts a valid hello and publishes limits for this generation.
type ConnectReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_open_channels is the maximum number of simultaneously nonterminal
	// channel IDs, including OpenChannel frames awaiting OpenChannelAck. It MUST
	// be in the range 1..65535.
	MaxOpenChannels uint32 `protobuf:"varint,1,opt,name=max_open_channels,json=maxOpenChannels,proto3" json:"max_open_channels,omitempty"`
	// max_data_bytes is the maximum ChannelData.data length. It MUST be in the
	// range 1..65536; either peer resets a channel that exceeds it.
	MaxDataBytes  uint32 `protobuf:"varint,2,opt,name=max_data_bytes,json=maxDataBytes,proto3" json:"max_data_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReady) Reset() {
	*x = ConnectReady{}
	mi := &file_external_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReady) ProtoMessage() {}

func (x *ConnectReady) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReady.ProtoReflect.Descriptor instead.
func (*ConnectReady) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectReady) GetMaxOpenChannels() uint32 {
	if x != nil {
		return x.MaxOpenChannels
	}
	return 0
}

func (x *ConnectReady) GetMaxDataBytes() uint32 {
	if x != nil {
		return x.MaxDataBytes
	}
	return 0
}

// OpenChannel starts one logical ordered byte stream.
//
// channel_id zero is invalid. Client-opened IDs MUST be odd and server-opened
// IDs MUST be even, and an ID cannot be reused within a session generation.
// slot_id MUST name a slot from ConnectHello. Only the server may open
// EXECUTION_GRPC and ACTOR_INGRESS; only the client may open ACTOR_EGRESS.
// The receiver MUST answer exactly once with OpenChannelAck before either side
// sends ChannelData, HalfCloseChannel, or ResetChannel for the channel.
type OpenChannel struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Kind      ChannelKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=externalprovider.ChannelKind" json:"kind,omitempty"`
	SlotId    string                 `protobuf:"bytes,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// actor_egress is required only for a protocol-v3, client-opened
	// ACTOR_EGRESS channel and forbidden for every other kind/version. The CSR
	// contributes only its public key; all certificate identity is
	// server-derived. It is bounded to 16 KiB by the receiver.
	ActorEgress   *ActorEgressOpen `protobuf:"bytes,4,opt,name=actor_egress,json=actorEgress,proto3" json:"actor_egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannel) Reset() {
	*x = OpenChannel{}
	mi := &file_external_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannel) ProtoMessage() {}

func (x *OpenChannel) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannel.ProtoReflect.Descriptor instead.
func (*OpenChannel) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{16}
}

func (x *OpenChannel) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenChannel) GetKind() ChannelKind {
	if x != nil {
		return x.Kind
	}
	return ChannelKind_CHANNEL_KIND_UNSPECIFIED
}

func (x *OpenChannel) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *OpenChannel) GetActorEgress() *ActorEgressOpen {
	if x != nil {
		return x.ActorEgress
	}
	return nil
}

type ActorEgressOpen struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	CertificateSigningRequestDer []byte                 `protobuf:"bytes,1,opt,name=certificate_signing_request_der,json=certificateSigningRequestDer,proto3" json:"certificate_signing_request_der,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ActorEgressOpen) Reset() {
	*x = ActorEgressOpen{}
	mi := &file_external_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEgressOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEgressOpen) ProtoMessage() {}

func (x *ActorEgressOpen) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEgressOpen.ProtoReflect.Descriptor instead.
func (*ActorEgressOpen) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ActorEgressOpen) GetCertificateSigningRequestDer() []byte {
	if x != nil {
		return x.CertificateSigningRequestDer
	}
	return nil
}

// OpenChannelAck accepts or rejects a peer's OpenChannel.
type OpenChannelAck struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// accepted true opens the channel and requires error_message to be empty.
	// accepted false terminates it and requires a nonempty error_message.
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// error_message is bounded to 1024 UTF-8 bytes, must not contain secrets, and
	// is untrusted peer text that receivers must not log without sanitizing.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// actor_egress is required only when accepting a protocol-v3 ACTOR_EGRESS
	// channel and forbidden on rejection and for every other channel kind. The
	// leaf is first. No private key, gateway address, or destination is present.
	ActorEgress   *ActorEgressOpenAck `protobuf:"bytes,4,opt,name=actor_egress,json=actorEgress,proto3" json:"actor_egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelAck) Reset() {
	*x = OpenChannelAck{}
	mi := &file_external_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelAck) ProtoMessage() {}

func (x *OpenChannelAck) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelAck.ProtoReflect.Descriptor instead.
func (*OpenChannelAck) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{18}
}

func (x *OpenChannelAck) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenChannelAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OpenChannelAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OpenChannelAck) GetActorEgress() *ActorEgressOpenAck {
	if x != nil {
		return x.ActorEgress
	}
	return nil
}

type ActorEgressOpenAck struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CertificateChainDer   [][]byte               `protobuf:"bytes,1,rep,name=certificate_chain_der,json=certificateChainDer,proto3" json:"certificate_chain_der,omitempty"`
	GatewayServerName     string                 `protobuf:"bytes,2,opt,name=gateway_server_name,json=gatewayServerName,proto3" json:"gateway_server_name,omitempty"`
	GatewayTrustBundlePem []byte                 `protobuf:"bytes,3,opt,name=gateway_trust_bundle_pem,json=gatewayTrustBundlePem,proto3" json:"gateway_trust_bundle_pem,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActorEgressOpenAck) Reset() {
	*x = ActorEgressOpenAck{}
	mi := &file_external_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEgressOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEgressOpenAck) ProtoMessage() {}

func (x *ActorEgressOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEgressOpenAck.ProtoReflect.Descriptor instead.
func (*ActorEgressOpenAck) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ActorEgressOpenAck) GetCertificateChainDer() [][]byte {
	if x != nil {
		return x.CertificateChainDer
	}
	return nil
}

func (x *ActorEgressOpenAck) GetGatewayServerName() string {
	if x != nil {
		return x.GatewayServerName
	}
	return ""
}

func (x *ActorEgressOpenAck) GetGatewayTrustBundlePem() []byte {
	if x != nil {
		return x.GatewayTrustBundlePem
	}
	return nil
}

// ChannelData carries the next ordered bytes for an accepted channel. Either
// peer may send it. data MUST be nonempty and no larger than
// ConnectReady.max_data_bytes. Sending data before a successful OpenChannelAck,
// after this sender's HalfCloseChannel, or after either side's ResetChannel is
// a protocol error.
type ChannelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelData) Reset() {
	*x = ChannelData{}
	mi := &file_external_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelData) ProtoMessage() {}

func (x *ChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelData.ProtoReflect.Descriptor instead.
func (*ChannelData) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{20}
}

func (x *ChannelData) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// HalfCloseChannel ends the sender's data direction while leaving the peer's
// direction open. Each peer may send it at most once for an accepted channel.
type HalfCloseChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HalfCloseChannel) Reset() {
	*x = HalfCloseChannel{}
	mi := &file_external_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HalfCloseChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HalfCloseChannel) ProtoMessage() {}

func (x *HalfCloseChannel) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HalfCloseChannel.ProtoReflect.Descriptor instead.
func (*HalfCloseChannel) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{21}
}

func (x *HalfCloseChannel) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

// ResetChannel immediately terminates both directions of an accepted channel.
// Either peer may send it only after a successful OpenChannelAck. Later frames
// for that channel are invalid. Receivers MUST NOT log reason as trusted text.
type ResetChannel struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// grpc_code is a numeric canonical gRPC status code in the range 1..16. OK
	// (zero) and values outside the canonical range are invalid.
	GrpcCode uint32 `protobuf:"varint,2,opt,name=grpc_code,json=grpcCode,proto3" json:"grpc_code,omitempty"`
	// reason is bounded to 1024 UTF-8 bytes and must not contain secrets.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetChannel) Reset() {
	*x = ResetChannel{}
	mi := &file_external_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetChannel) ProtoMessage() {}

func (x *ResetChannel) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetChannel.ProtoReflect.Descriptor instead.
func (*ResetChannel) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{22}
}

func (x *ResetChannel) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ResetChannel) GetGrpcCode() uint32 {
	if x != nil {
		return x.GrpcCode
	}
	return 0
}

func (x *ResetChannel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Heartbeat detects a dead session without creating a logical channel. Either
// peer may send a probe after ConnectReady; the receiver answers with the same
// nonce and acknowledgement=true. An acknowledgement is never acknowledged.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nonce must be nonzero.
	Nonce           uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Acknowledgement bool   `protobuf:"varint,2,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_external_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_external_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_external_provider_proto_rawDescGZIP(), []int{23}
}

func (x *Heartbeat) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Heartbeat) GetAcknowledgement() bool {
	if x != nil {
		return x.Acknowledgement
	}
	return false
}

var File_external_provider_proto protoreflect.FileDescriptor

const file_external_provider_proto_rawDesc = "" +
	"\n" +
	"\x17external_provider.proto\x12\x10externalprovider\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\fateapi.proto\"\xfa\x01\n" +
	"\x1fExternalProviderEnrollmentScope\x12%\n" +
	"\x0eowner_atespace\x18\x01 \x01(\tR\rownerAtespace\x12)\n" +
	"\x10worker_namespace\x18\x02 \x01(\tR\x0fworkerNamespace\x12\x1f\n" +
	"\vworker_pool\x18\x03 \x01(\tR\n" +
	"workerPool\x12\x1b\n" +
	"\tmax_slots\x18\x04 \x01(\rR\bmaxSlots\x12G\n" +
	"\vslot_policy\x18\x05 \x01(\v2&.externalprovider.SlotCapabilityPolicyR\n" +
	"slotPolicy\"\x9f\x01\n" +
	"'CreateExternalProviderEnrollmentRequest\x12G\n" +
	"\x05scope\x18\x01 \x01(\v21.externalprovider.ExternalProviderEnrollmentScopeR\x05scope\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x8f\x02\n" +
	"(CreateExternalProviderEnrollmentResponse\x12%\n" +
	"\x0eenrollment_uid\x18\x01 \x01(\tR\renrollmentUid\x128\n" +
	"\x15enrollment_credential\x18\x02 \x01(\fB\x03\x80\x01\x01R\x14enrollmentCredential\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12G\n" +
	"\x05scope\x18\x04 \x01(\v21.externalprovider.ExternalProviderEnrollmentScopeR\x05scope\"V\n" +
	")RevokeExternalProviderRegistrationRequest\x12)\n" +
	"\x10registration_uid\x18\x01 \x01(\tR\x0fregistrationUid\",\n" +
	"*RevokeExternalProviderRegistrationResponse\"\x0f\n" +
	"\rEnrollRequest\"\xb8\x01\n" +
	"\x0eEnrollResponse\x12)\n" +
	"\x10registration_uid\x18\x01 \x01(\tR\x0fregistrationUid\x122\n" +
	"\x12refresh_credential\x18\x02 \x01(\fB\x03\x80\x01\x01R\x11refreshCredential\x12G\n" +
	"\vslot_policy\x18\x03 \x01(\v2&.externalprovider.SlotCapabilityPolicyR\n" +
	"slotPolicy\"D\n" +
	"\x17MintSessionTokenRequest\x12)\n" +
	"\x10registration_uid\x18\x01 \x01(\tR\x0fregistrationUid\"\xc8\x01\n" +
	"\x18MintSessionTokenResponse\x12(\n" +
	"\rsession_token\x18\x01 \x01(\fB\x03\x80\x01\x01R\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12G\n" +
	"\vslot_policy\x18\x03 \x01(\v2&.externalprovider.SlotCapabilityPolicyR\n" +
	"slotPolicy\"\xe0\x03\n" +
	"\vClientFrame\x12-\n" +
	"\x12session_generation\x18\x01 \x01(\x04R\x11sessionGeneration\x126\n" +
	"\x05hello\x18\x02 \x01(\v2\x1e.externalprovider.ConnectHelloH\x00R\x05hello\x123\n" +
	"\x04open\x18\x03 \x01(\v2\x1d.externalprovider.OpenChannelH\x00R\x04open\x12=\n" +
	"\bopen_ack\x18\x04 \x01(\v2 .externalprovider.OpenChannelAckH\x00R\aopenAck\x123\n" +
	"\x04data\x18\x05 \x01(\v2\x1d.externalprovider.ChannelDataH\x00R\x04data\x12C\n" +
	"\n" +
	"half_close\x18\x06 \x01(\v2\".externalprovider.HalfCloseChannelH\x00R\thalfClose\x126\n" +
	"\x05reset\x18\a \x01(\v2\x1e.externalprovider.ResetChannelH\x00R\x05reset\x12;\n" +
	"\theartbeat\x18\b \x01(\v2\x1b.externalprovider.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05frame\"\xe0\x03\n" +
	"\vServerFrame\x12-\n" +
	"\x12session_generation\x18\x01 \x01(\x04R\x11sessionGeneration\x126\n" +
	"\x05ready\x18\x02 \x01(\v2\x1e.externalprovider.ConnectReadyH\x00R\x05ready\x123\n" +
	"\x04open\x18\x03 \x01(\v2\x1d.externalprovider.OpenChannelH\x00R\x04open\x12=\n" +
	"\bopen_ack\x18\x04 \x01(\v2 .externalprovider.OpenChannelAckH\x00R\aopenAck\x123\n" +
	"\x04data\x18\x05 \x01(\v2\x1d.externalprovider.ChannelDataH\x00R\x04data\x12C\n" +
	"\n" +
	"half_close\x18\x06 \x01(\v2\".externalprovider.HalfCloseChannelH\x00R\thalfClose\x126\n" +
	"\x05reset\x18\a \x01(\v2\x1e.externalprovider.ResetChannelH\x00R\x05reset\x12;\n" +
	"\theartbeat\x18\b \x01(\v2\x1b.externalprovider.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05frame\"\xc8\x01\n" +
	"\fConnectHello\x12)\n" +
	"\x10registration_uid\x18\x01 \x01(\tR\x0fregistrationUid\x124\n" +
	"\x05slots\x18\x02 \x03(\v2\x1e.externalprovider.ExternalSlotR\x05slots\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12,\n" +
	"\x12slot_policy_digest\x18\x04 \x01(\tR\x10slotPolicyDigest\"\x9e\x02\n" +
	"\fExternalSlot\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12#\n" +
	"\rsandbox_class\x18\x02 \x01(\tR\fsandboxClass\x12B\n" +
	"\x06labels\x18\x03 \x03(\v2*.externalprovider.ExternalSlot.LabelsEntryR\x06labels\x122\n" +
	"\bcapacity\x18\x04 \x01(\v2\x16.ateapi.WorkerCapacityR\bcapacity\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\tR\tprofileId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x14SlotCapabilityPolicy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x129\n" +
	"\bprofiles\x18\x03 \x03(\v2\x1d.externalprovider.SlotProfileR\bprofiles\"\xa0\x02\n" +
	"\vSlotProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12#\n" +
	"\rsandbox_class\x18\x02 \x01(\tR\fsandboxClass\x12A\n" +
	"\x06labels\x18\x03 \x03(\v2).externalprovider.SlotProfile.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tmax_slots\x18\x04 \x01(\rR\bmaxSlots\x122\n" +
	"\bcapacity\x18\x05 \x01(\v2\x16.ateapi.WorkerCapacityR\bcapacity\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\fConnectReady\x12*\n" +
	"\x11max_open_channels\x18\x01 \x01(\rR\x0fmaxOpenChannels\x12$\n" +
	"\x0emax_data_bytes\x18\x02 \x01(\rR\fmaxDataBytes\"\xbe\x01\n" +
	"\vOpenChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.externalprovider.ChannelKindR\x04kind\x12\x17\n" +
	"\aslot_id\x18\x03 \x01(\tR\x06slotId\x12D\n" +
	"\factor_egress\x18\x04 \x01(\v2!.externalprovider.ActorEgressOpenR\vactorEgress\"]\n" +
	"\x0fActorEgressOpen\x12J\n" +
	"\x1fcertificate_signing_request_der\x18\x01 \x01(\fB\x03\x80\x01\x01R\x1ccertificateSigningRequestDer\"\xbe\x01\n" +
	"\x0eOpenChannelAck\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tB\x03\x80\x01\x01R\ferrorMessage\x12G\n" +
	"\factor_egress\x18\x04 \x01(\v2$.externalprovider.ActorEgressOpenAckR\vactorEgress\"\xbb\x01\n" +
	"\x12ActorEgressOpenAck\x127\n" +
	"\x15certificate_chain_der\x18\x01 \x03(\fB\x03\x80\x01\x01R\x13certificateChainDer\x12.\n" +
	"\x13gateway_server_name\x18\x02 \x01(\tR\x11gatewayServerName\x12<\n" +
	"\x18gateway_trust_bundle_pem\x18\x03 \x01(\fB\x03\x80\x01\x01R\x15gatewayTrustBundlePem\"E\n" +
	"\vChannelData\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fB\x03\x80\x01\x01R\x04data\"1\n" +
	"\x10HalfCloseChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\"g\n" +
	"\fResetChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x1b\n" +
	"\tgrpc_code\x18\x02 \x01(\rR\bgrpcCode\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tB\x03\x80\x01\x01R\x06reason\"K\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12(\n" +
	"\x0facknowledgement\x18\x02 \x01(\bR\x0facknowledgement*\x8b\x01\n" +
	"\vChannelKind\x12\x1c\n" +
	"\x18CHANNEL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCHANNEL_KIND_EXECUTION_GRPC\x10\x01\x12\x1e\n" +
	"\x1aCHANNEL_KIND_ACTOR_INGRESS\x10\x02\x12\x1d\n" +
	"\x19CHANNEL_KIND_ACTOR_EGRESS\x10\x032\xa3\x02\n" +
	"\x16ExternalProviderBroker\x12M\n" +
	"\x06Enroll\x12\x1f.externalprovider.EnrollRequest\x1a .externalprovider.EnrollResponse\"\x00\x12k\n" +
	"\x10MintSessionToken\x12).externalprovider.MintSessionTokenRequest\x1a*.externalprovider.MintSessionTokenResponse\"\x00\x12M\n" +
	"\aConnect\x12\x1d.externalprovider.ClientFrame\x1a\x1d.externalprovider.ServerFrame\"\x00(\x010\x012\xd9\x02\n" +
	"\x15ExternalProviderAdmin\x12\x9b\x01\n" +
	" CreateExternalProviderEnrollment\x129.externalprovider.CreateExternalProviderEnrollmentRequest\x1a:.externalprovider.CreateExternalProviderEnrollmentResponse\"\x00\x12\xa1\x01\n" +
	"\"RevokeExternalProviderRegistration\x12;.externalprovider.RevokeExternalProviderRegistrationRequest\x1a<.externalprovider.RevokeExternalProviderRegistrationResponse\"\x00BCZAgithub.com/agent-substrate/substrate/pkg/proto/externalproviderpbb\x06proto3"

var (
	file_external_provider_proto_rawDescOnce sync.Once
	file_external_provider_proto_rawDescData []byte
)

func file_external_provider_proto_rawDescGZIP() []byte {
	file_external_provider_proto_rawDescOnce.Do(func() {
		file_external_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_external_provider_proto_rawDesc), len(file_external_provider_proto_rawDesc)))
	})
	return file_external_provider_proto_rawDescData
}

var file_external_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_external_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_external_provider_proto_goTypes = []any{
	(ChannelKind)(0),                                   // 0: externalprovider.ChannelKind
	(*ExternalProviderEnrollmentScope)(nil),            // 1: externalprovider.ExternalProviderEnrollmentScope
	(*CreateExternalProviderEnrollmentRequest)(nil),    // 2: externalprovider.CreateExternalProviderEnrollmentRequest
	(*CreateExternalProviderEnrollmentResponse)(nil),   // 3: externalprovider.CreateExternalProviderEnrollmentResponse
	(*RevokeExternalProviderRegistrationRequest)(nil),  // 4: externalprovider.RevokeExternalProviderRegistrationRequest
	(*RevokeExternalProviderRegistrationResponse)(nil), // 5: externalprovider.RevokeExternalProviderRegistrationResponse
	(*EnrollRequest)(nil),                              // 6: externalprovider.EnrollRequest
	(*EnrollResponse)(nil),                             // 7: externalprovider.EnrollResponse
	(*MintSessionTokenRequest)(nil),                    // 8: externalprovider.MintSessionTokenRequest
	(*MintSessionTokenResponse)(nil),                   // 9: externalprovider.MintSessionTokenResponse
	(*ClientFrame)(nil),                                // 10: externalprovider.ClientFrame
	(*ServerFrame)(nil),                                // 11: externalprovider.ServerFrame
	(*ConnectHello)(nil),                               // 12: externalprovider.ConnectHello
	(*ExternalSlot)(nil),                               // 13: externalprovider.ExternalSlot
	(*SlotCapabilityPolicy)(nil),                       // 14: externalprovider.SlotCapabilityPolicy
	(*SlotProfile)(nil),                                // 15: externalprovider.SlotProfile
	(*ConnectReady)(nil),                               // 16: externalprovider.ConnectReady
	(*OpenChannel)(nil),                                // 17: externalprovider.OpenChannel
	(*ActorEgressOpen)(nil),                            // 18: externalprovider.ActorEgressOpen
	(*OpenChannelAck)(nil),                             // 19: externalprovider.OpenChannelAck
	(*ActorEgressOpenAck)(nil),                         // 20: externalprovider.ActorEgressOpenAck
	(*ChannelData)(nil),                                // 21: externalprovider.ChannelData
	(*HalfCloseChannel)(nil),                           // 22: externalprovider.HalfCloseChannel
	(*ResetChannel)(nil),                               // 23: externalprovider.ResetChannel
	(*Heartbeat)(nil),                                  // 24: externalprovider.Heartbeat
	nil,                                                // 25: externalprovider.ExternalSlot.LabelsEntry
	nil,                                                // 26: externalprovider.SlotProfile.LabelsEntry
	(*durationpb.Duration)(nil),                        // 27: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                      // 28: google.protobuf.Timestamp
	(*ateapipb.WorkerCapacity)(nil),                    // 29: ateapi.WorkerCapacity
}
var file_external_provider_proto_depIdxs = []int32{
	14, // 0: externalprovider.ExternalProviderEnrollmentScope.slot_policy:type_name -> externalprovider.SlotCapabilityPolicy
	1,  // 1: externalprovider.CreateExternalProviderEnrollmentRequest.scope:type_name -> externalprovider.ExternalProviderEnrollmentScope
	27, // 2: externalprovider.CreateExternalProviderEnrollmentRequest.ttl:type_name -> google.protobuf.Duration
	28, // 3: externalprovider.CreateExternalProviderEnrollmentResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: externalprovider.CreateExternalProviderEnrollmentResponse.scope:type_name -> externalprovider.ExternalProviderEnrollmentScope
	14, // 5: externalprovider.EnrollResponse.slot_policy:type_name -> externalprovider.SlotCapabilityPolicy
	28, // 6: externalprovider.MintSessionTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 7: externalprovider.MintSessionTokenResponse.slot_policy:type_name -> externalprovider.SlotCapabilityPolicy
	12, // 8: externalprovider.ClientFrame.hello:type_name -> externalprovider.ConnectHello
	17, // 9: externalprovider.ClientFrame.open:type_name -> externalprovider.OpenChannel
	19, // 10: externalprovider.ClientFrame.open_ack:type_name -> externalprovider.OpenChannelAck
	21, // 11: externalprovider.ClientFrame.data:type_name -> externalprovider.ChannelData
	22, // 12: externalprovider.ClientFrame.half_close:type_name -> externalprovider.HalfCloseChannel
	23, // 13: externalprovider.ClientFrame.reset:type_name -> externalprovider.ResetChannel
	24, // 14: externalprovider.ClientFrame.heartbeat:type_name -> externalprovider.Heartbeat
	16, // 15: externalprovider.ServerFrame.ready:type_name -> externalprovider.ConnectReady
	17, // 16: externalprovider.ServerFrame.open:type_name -> externalprovider.OpenChannel
	19, // 17: externalprovider.ServerFrame.open_ack:type_name -> externalprovider.OpenChannelAck
	21, // 18: externalprovider.ServerFrame.data:type_name -> externalprovider.ChannelData
	22, // 19: externalprovider.ServerFrame.half_close:type_name -> externalprovider.HalfCloseChannel
	23, // 20: externalprovider.ServerFrame.reset:type_name -> externalprovider.ResetChannel
	24, // 21: externalprovider.ServerFrame.heartbeat:type_name -> externalprovider.Heartbeat
	13, // 22: externalprovider.ConnectHello.slots:type_name -> externalprovider.ExternalSlot
	25, // 23: externalprovider.ExternalSlot.labels:type_name -> externalprovider.ExternalSlot.LabelsEntry
	29, // 24: externalprovider.ExternalSlot.capacity:type_name -> ateapi.WorkerCapacity
	15, // 25: externalprovider.SlotCapabilityPolicy.profiles:type_name -> externalprovider.SlotProfile
	26, // 26: externalprovider.SlotProfile.labels:type_name -> externalprovider.SlotProfile.LabelsEntry
	29, // 27: externalprovider.SlotProfile.capacity:type_name -> ateapi.WorkerCapacity
	0,  // 28: externalprovider.OpenChannel.kind:type_name -> externalprovider.ChannelKind
	18, // 29: externalprovider.OpenChannel.actor_egress:type_name -> externalprovider.ActorEgressOpen
	20, // 30: externalprovider.OpenChannelAck.actor_egress:type_name -> externalprovider.ActorEgressOpenAck
	6,  // 31: externalprovider.ExternalProviderBroker.Enroll:input_type -> externalprovider.EnrollRequest
	8,  // 32: externalprovider.ExternalProviderBroker.MintSessionToken:input_type -> externalprovider.MintSessionTokenRequest
	10, // 33: externalprovider.ExternalProviderBroker.Connect:input_type -> externalprovider.ClientFrame
	2,  // 34: externalprovider.ExternalProviderAdmin.CreateExternalProviderEnrollment:input_type -> externalprovider.CreateExternalProviderEnrollmentRequest
	4,  // 35: externalprovider.ExternalProviderAdmin.RevokeExternalProviderRegistration:input_type -> externalprovider.RevokeExternalProviderRegistrationRequest
	7,  // 36: externalprovider.ExternalProviderBroker.Enroll:output_type -> externalprovider.EnrollResponse
	9,  // 37: externalprovider.ExternalProviderBroker.MintSessionToken:output_type -> externalprovider.MintSessionTokenResponse
	11, // 38: externalprovider.ExternalProviderBroker.Connect:output_type -> externalprovider.ServerFrame
	3,  // 39: externalprovider.ExternalProviderAdmin.CreateExternalProviderEnrollment:output_type -> externalprovider.CreateExternalProviderEnrollmentResponse
	5,  // 40: externalprovider.ExternalProviderAdmin.RevokeExternalProviderRegistration:output_type -> externalprovider.RevokeExternalProviderRegistrationResponse
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_external_provider_proto_init() }
func file_external_provider_proto_init() {
	if File_external_provider_proto != nil {
		return
	}
	file_external_provider_proto_msgTypes[9].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Open)(nil),
		(*ClientFrame_OpenAck)(nil),
		(*ClientFrame_Data)(nil),
		(*ClientFrame_HalfClose)(nil),
		(*ClientFrame_Reset_)(nil),
		(*ClientFrame_Heartbeat)(nil),
	}
	file_external_provider_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerFrame_Ready)(nil),
		(*ServerFrame_Open)(nil),
		(*ServerFrame_OpenAck)(nil),
		(*ServerFrame_Data)(nil),
		(*ServerFrame_HalfClose)(nil),
		(*ServerFrame_Reset_)(nil),
		(*ServerFrame_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_external_provider_proto_rawDesc), len(file_external_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_external_provider_proto_goTypes,
		DependencyIndexes: file_external_provider_proto_depIdxs,
		EnumInfos:         file_external_provider_proto_enumTypes,
		MessageInfos:      file_external_provider_proto_msgTypes,
	}.Build()
	File_external_provider_proto = out.File
	file_external_provider_proto_goTypes = nil
	file_external_provider_proto_depIdxs = nil
}
