// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: external_provider.proto

package externalproviderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalProviderBroker_Enroll_FullMethodName           = "/externalprovider.ExternalProviderBroker/Enroll"
	ExternalProviderBroker_MintSessionToken_FullMethodName = "/externalprovider.ExternalProviderBroker/MintSessionToken"
	ExternalProviderBroker_Connect_FullMethodName          = "/externalprovider.ExternalProviderBroker/Connect"
)

// ExternalProviderBrokerClient is the client API for ExternalProviderBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExternalProviderBroker enrolls an external provider registration and accepts
// its authenticated, outbound-only live session. These credentials are scoped
// to this service; they are not credentials for the general ateapi Control API.
//
// Every RPC carries exactly one lowercase gRPC `authorization` metadata value
// in the form `Bearer <token>`. Enroll uses an out-of-band enrollment token,
// MintSessionToken uses the refresh credential returned by Enroll, and Connect
// uses the session token returned by MintSessionToken. Credential bytes are
// unpadded base64url token bytes (`A-Z`, `a-z`, `0-9`, `_`, `-`) and exclude
// the `Bearer ` prefix. Credentials never appear in request messages or
// ConnectHello. Every production RPC MUST use server-authenticated TLS;
// plaintext transport is permitted only in an explicitly isolated test mode.
type ExternalProviderBrokerClient interface {
	// Enroll exchanges a scoped, single-use enrollment token for a durable
	// registration UID and refresh credential. It is not safe to retry
	// automatically after an ambiguous response loss; recovery requires a new
	// enrollment token or an operator-assisted lookup of the registration.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// MintSessionToken exchanges a registration-scoped refresh credential for a
	// short-lived token accepted only by Connect.
	MintSessionToken(ctx context.Context, in *MintSessionTokenRequest, opts ...grpc.CallOption) (*MintSessionTokenResponse, error)
	// Connect establishes one authenticated live session. The client initiates
	// the network connection and both sides multiplex bounded byte streams over
	// it; no client listener or persisted live endpoint is part of this API.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type externalProviderBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalProviderBrokerClient(cc grpc.ClientConnInterface) ExternalProviderBrokerClient {
	return &externalProviderBrokerClient{cc}
}

func (c *externalProviderBrokerClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, ExternalProviderBroker_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderBrokerClient) MintSessionToken(ctx context.Context, in *MintSessionTokenRequest, opts ...grpc.CallOption) (*MintSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintSessionTokenResponse)
	err := c.cc.Invoke(ctx, ExternalProviderBroker_MintSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderBrokerClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExternalProviderBroker_ServiceDesc.Streams[0], ExternalProviderBroker_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalProviderBroker_ConnectClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// ExternalProviderBrokerServer is the server API for ExternalProviderBroker service.
// All implementations must embed UnimplementedExternalProviderBrokerServer
// for forward compatibility.
//
// ExternalProviderBroker enrolls an external provider registration and accepts
// its authenticated, outbound-only live session. These credentials are scoped
// to this service; they are not credentials for the general ateapi Control API.
//
// Every RPC carries exactly one lowercase gRPC `authorization` metadata value
// in the form `Bearer <token>`. Enroll uses an out-of-band enrollment token,
// MintSessionToken uses the refresh credential returned by Enroll, and Connect
// uses the session token returned by MintSessionToken. Credential bytes are
// unpadded base64url token bytes (`A-Z`, `a-z`, `0-9`, `_`, `-`) and exclude
// the `Bearer ` prefix. Credentials never appear in request messages or
// ConnectHello. Every production RPC MUST use server-authenticated TLS;
// plaintext transport is permitted only in an explicitly isolated test mode.
type ExternalProviderBrokerServer interface {
	// Enroll exchanges a scoped, single-use enrollment token for a durable
	// registration UID and refresh credential. It is not safe to retry
	// automatically after an ambiguous response loss; recovery requires a new
	// enrollment token or an operator-assisted lookup of the registration.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// MintSessionToken exchanges a registration-scoped refresh credential for a
	// short-lived token accepted only by Connect.
	MintSessionToken(context.Context, *MintSessionTokenRequest) (*MintSessionTokenResponse, error)
	// Connect establishes one authenticated live session. The client initiates
	// the network connection and both sides multiplex bounded byte streams over
	// it; no client listener or persisted live endpoint is part of this API.
	Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedExternalProviderBrokerServer()
}

// UnimplementedExternalProviderBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalProviderBrokerServer struct{}

func (UnimplementedExternalProviderBrokerServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedExternalProviderBrokerServer) MintSessionToken(context.Context, *MintSessionTokenRequest) (*MintSessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintSessionToken not implemented")
}
func (UnimplementedExternalProviderBrokerServer) Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedExternalProviderBrokerServer) mustEmbedUnimplementedExternalProviderBrokerServer() {
}
func (UnimplementedExternalProviderBrokerServer) testEmbeddedByValue() {}

// UnsafeExternalProviderBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalProviderBrokerServer will
// result in compilation errors.
type UnsafeExternalProviderBrokerServer interface {
	mustEmbedUnimplementedExternalProviderBrokerServer()
}

func RegisterExternalProviderBrokerServer(s grpc.ServiceRegistrar, srv ExternalProviderBrokerServer) {
	// If the following call panics, it indicates UnimplementedExternalProviderBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalProviderBroker_ServiceDesc, srv)
}

func _ExternalProviderBroker_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderBrokerServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProviderBroker_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderBrokerServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProviderBroker_MintSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderBrokerServer).MintSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProviderBroker_MintSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderBrokerServer).MintSessionToken(ctx, req.(*MintSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProviderBroker_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExternalProviderBrokerServer).Connect(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalProviderBroker_ConnectServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// ExternalProviderBroker_ServiceDesc is the grpc.ServiceDesc for ExternalProviderBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalProviderBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "externalprovider.ExternalProviderBroker",
	HandlerType: (*ExternalProviderBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _ExternalProviderBroker_Enroll_Handler,
		},
		{
			MethodName: "MintSessionToken",
			Handler:    _ExternalProviderBroker_MintSessionToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ExternalProviderBroker_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "external_provider.proto",
}
